THUNDERDEN_VERSION = 0.0.1
THUNDERDEN_SITE = $(BR2_EXTERNAL_THUNDERDEN_PATH)/..
THUNDERDEN_SITE_METHOD = local
THUNDERDEN_SUPPORTS_IN_SOURCE_BUILD = NO
THUNDERDEN_DEPENDENCIES = boost openssl zbar libv4l libqrencode
THUNDERDEN_USERS = signer 1000 signer 1000 * /run /bin/false - Signer
THUNDERDEN_CONF_OPTS = -DTD_BUILD_TESTS=OFF -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=MinSizeRel \
	-DCORE_SOURCE_DIR=/opt/bitcoin -DUR_SOURCE_DIR=/opt/bc-ur \
	-DBIP39_WORDLIST=/opt/bip39-english.txt \
	-DBIP39_WORDLIST_SHA256=$(BIP39_WORDLIST_SHA256) \n	-DBIP39_CHINESE_WORDLIST=/opt/bip39-chinese.txt \n	-DBIP39_CHINESE_WORDLIST_SHA256=$(BIP39_CHINESE_WORDLIST_SHA256) \n	-DUNIFONT_HEX=/opt/unifont.hex -DUNIFONT_HEX_SHA256=$(UNIFONT_HEX_SHA256)

$(eval $(cmake-package))
